trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'YourDockerRegistryServiceConnection' # Replace with your actual service connection name
  imageRepository: 'my-nestjs-app'
  containerRegistry: 'yourdockerhubusername' # Replace with your Docker Hub username or your container registry
  dockerfilePath: '**/Dockerfile'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '18.x'

  - script: npm install
    displayName: 'Install Dependencies'

  - script: npm run build
    displayName: 'Build Application'

  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      containerRegistry: '$(dockerRegistryServiceConnection)'
      repository: '$(containerRegistry)/$(imageRepository)'
      command: 'buildAndPush'
      Dockerfile: '$(dockerfilePath)'
      tags: |
        $(Build.BuildId)

  - script: npx swagger-cli bundle ./src/main.ts -o openapi.json --type yaml
    displayName: 'Generate OpenAPI Spec'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish OpenAPI Spec'
    inputs:
      PathtoPublish: 'openapi.json'
      ArtifactName: 'OpenAPISpec'
