version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=yourpassword  # Replace with your actual password
      - DB_DATABASE=mydatabase
    depends_on:
      - postgres
      - datadog  # Ensure the app waits for datadog to be ready
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword  # Replace with your actual password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=your_datadog_api_key  # Replace with your Datadog API key
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
