apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nestjs-boilerplate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/yourusername/nestjs-boilerplate.git'
    targetRevision: HEAD
    path: 'k8s'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
